package net.wavedk.extrautilitiesreutilized.procedures;

import net.minecraft.world.item.Items;
import net.minecraft.core.registries.BuiltInRegistries;

public class CGenCFGManagerProcedure {
	public static com.google.gson.JsonObject execute() {
		com.google.gson.JsonObject cItemOBJ = new com.google.gson.JsonObject();
		com.google.gson.JsonObject configJsonObject = new com.google.gson.JsonObject();
		com.google.gson.JsonObject cgenfp = new com.google.gson.JsonObject();
		com.google.gson.JsonObject cgenobj = new com.google.gson.JsonObject();
		String cItem = "";
		com.google.gson.JsonArray cgenarray = new com.google.gson.JsonArray();
		cItem = BuiltInRegistries.ITEM.getKey(Items.ENCHANTED_GOLDEN_APPLE).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 6400);
		cItemOBJ.addProperty("feSpeed", 96);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.GOLDEN_APPLE).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 1800);
		cItemOBJ.addProperty("feSpeed", 48);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.GOLDEN_CARROT).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 480);
		cItemOBJ.addProperty("feSpeed", 24);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.CHORUS_FRUIT).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 960);
		cItemOBJ.addProperty("feSpeed", 32);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.GLOW_BERRIES).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 320);
		cItemOBJ.addProperty("feSpeed", 24);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.POISONOUS_POTATO).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 320);
		cItemOBJ.addProperty("feSpeed", 24);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.BAKED_POTATO).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 320);
		cItemOBJ.addProperty("feSpeed", 24);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.COOKED_BEEF).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 720);
		cItemOBJ.addProperty("feSpeed", 32);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.COOKED_PORKCHOP).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 720);
		cItemOBJ.addProperty("feSpeed", 32);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.COOKED_MUTTON).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 720);
		cItemOBJ.addProperty("feSpeed", 32);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.COOKED_CHICKEN).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 720);
		cItemOBJ.addProperty("feSpeed", 32);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.COOKED_RABBIT).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 720);
		cItemOBJ.addProperty("feSpeed", 32);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.SUSPICIOUS_STEW).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 480);
		cItemOBJ.addProperty("feSpeed", 32);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.RABBIT_STEW).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 480);
		cItemOBJ.addProperty("feSpeed", 32);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.BEETROOT_SOUP).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 480);
		cItemOBJ.addProperty("feSpeed", 32);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.MUSHROOM_STEW).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 480);
		cItemOBJ.addProperty("feSpeed", 32);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.PUMPKIN_PIE).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 480);
		cItemOBJ.addProperty("feSpeed", 32);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.CAKE).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 1280);
		cItemOBJ.addProperty("feSpeed", 48);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.COOKIE).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 480);
		cItemOBJ.addProperty("feSpeed", 32);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.BREAD).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 480);
		cItemOBJ.addProperty("feSpeed", 32);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.COOKED_SALMON).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 240);
		cItemOBJ.addProperty("feSpeed", 16);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.COOKED_COD).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 240);
		cItemOBJ.addProperty("feSpeed", 16);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.PUFFERFISH).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 160);
		cItemOBJ.addProperty("feSpeed", 16);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.TROPICAL_FISH).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 160);
		cItemOBJ.addProperty("feSpeed", 16);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.SALMON).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 160);
		cItemOBJ.addProperty("feSpeed", 16);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.COD).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 160);
		cItemOBJ.addProperty("feSpeed", 16);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.RABBIT).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 320);
		cItemOBJ.addProperty("feSpeed", 24);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.CHICKEN).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 320);
		cItemOBJ.addProperty("feSpeed", 24);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.MUTTON).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 320);
		cItemOBJ.addProperty("feSpeed", 24);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.PORKCHOP).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 320);
		cItemOBJ.addProperty("feSpeed", 24);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.BEEF).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 320);
		cItemOBJ.addProperty("feSpeed", 24);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.DRIED_KELP).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 240);
		cItemOBJ.addProperty("feSpeed", 24);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.BEETROOT).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 240);
		cItemOBJ.addProperty("feSpeed", 24);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.POTATO).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 240);
		cItemOBJ.addProperty("feSpeed", 24);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.SWEET_BERRIES).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 240);
		cItemOBJ.addProperty("feSpeed", 24);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.CARROT).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 240);
		cItemOBJ.addProperty("feSpeed", 24);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.MELON_SLICE).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 240);
		cItemOBJ.addProperty("feSpeed", 24);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.APPLE).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 480);
		cItemOBJ.addProperty("feSpeed", 24);
		cgenfp.add(cItem, cItemOBJ);
		cgenarray.add(cItem);
		cgenobj.add("listFuel", cgenarray);
		cgenobj.add("fuelProperties", cgenfp);
		return cgenobj;
	}
}