package net.wavedk.extrautilitiesreutilized.procedures;

import net.wavedk.extrautilitiesreutilized.network.EuruModVariables;
import net.wavedk.extrautilitiesreutilized.init.EuruModItems;
import net.wavedk.extrautilitiesreutilized.init.EuruModBlocks;

import net.neoforged.fml.loading.FMLPaths;

import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.item.Items;
import net.minecraft.core.registries.BuiltInRegistries;

import java.io.IOException;
import java.io.FileWriter;
import java.io.FileReader;
import java.io.File;
import java.io.BufferedReader;

public class EURUGeneratorsManagerProcedure {
	public static void execute() {
		File configFile = new File("");
		File file = new File("");
		double cVer = 0;
		String cItem = "";
		com.google.gson.JsonObject configSubJsonObjest = new com.google.gson.JsonObject();
		com.google.gson.JsonObject configJsonObject = new com.google.gson.JsonObject();
		com.google.gson.JsonObject fuelPropertiesOBJ = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coalOBJ = new com.google.gson.JsonObject();
		com.google.gson.JsonObject saplingsobj = new com.google.gson.JsonObject();
		com.google.gson.JsonObject logsobj = new com.google.gson.JsonObject();
		com.google.gson.JsonObject planksobj = new com.google.gson.JsonObject();
		com.google.gson.JsonObject stickobj = new com.google.gson.JsonObject();
		com.google.gson.JsonObject wool = new com.google.gson.JsonObject();
		com.google.gson.JsonObject carpet = new com.google.gson.JsonObject();
		com.google.gson.JsonObject day = new com.google.gson.JsonObject();
		com.google.gson.JsonObject wsword = new com.google.gson.JsonObject();
		com.google.gson.JsonObject waxe = new com.google.gson.JsonObject();
		com.google.gson.JsonObject wpick = new com.google.gson.JsonObject();
		com.google.gson.JsonObject wsho = new com.google.gson.JsonObject();
		com.google.gson.JsonObject whoe = new com.google.gson.JsonObject();
		com.google.gson.JsonObject shield = new com.google.gson.JsonObject();
		com.google.gson.JsonObject stickcarrot = new com.google.gson.JsonObject();
		com.google.gson.JsonObject warpstick = new com.google.gson.JsonObject();
		com.google.gson.JsonObject bookshelf = new com.google.gson.JsonObject();
		com.google.gson.JsonObject cbookshelf = new com.google.gson.JsonObject();
		com.google.gson.JsonObject button = new com.google.gson.JsonObject();
		com.google.gson.JsonObject wooden_doors = new com.google.gson.JsonObject();
		com.google.gson.JsonObject wooden_fences = new com.google.gson.JsonObject();
		com.google.gson.JsonObject wooden_pressure_plates = new com.google.gson.JsonObject();
		com.google.gson.JsonObject wooden_slabs = new com.google.gson.JsonObject();
		com.google.gson.JsonObject wooden_stairs = new com.google.gson.JsonObject();
		com.google.gson.JsonObject wooden_trapdoors = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coalblock = new com.google.gson.JsonObject();
		com.google.gson.JsonObject craft = new com.google.gson.JsonObject();
		com.google.gson.JsonObject chest = new com.google.gson.JsonObject();
		com.google.gson.JsonObject tchest = new com.google.gson.JsonObject();
		com.google.gson.JsonObject ladder = new com.google.gson.JsonObject();
		com.google.gson.JsonObject juke = new com.google.gson.JsonObject();
		com.google.gson.JsonObject bowl = new com.google.gson.JsonObject();
		com.google.gson.JsonObject signs = new com.google.gson.JsonObject();
		com.google.gson.JsonObject bow = new com.google.gson.JsonObject();
		com.google.gson.JsonObject cbow = new com.google.gson.JsonObject();
		com.google.gson.JsonObject boats = new com.google.gson.JsonObject();
		com.google.gson.JsonObject beds = new com.google.gson.JsonObject();
		com.google.gson.JsonObject beehive = new com.google.gson.JsonObject();
		com.google.gson.JsonObject torch = new com.google.gson.JsonObject();
		com.google.gson.JsonObject torchred = new com.google.gson.JsonObject();
		com.google.gson.JsonObject torchsoul = new com.google.gson.JsonObject();
		com.google.gson.JsonObject cart = new com.google.gson.JsonObject();
		com.google.gson.JsonObject fletch = new com.google.gson.JsonObject();
		com.google.gson.JsonObject smith = new com.google.gson.JsonObject();
		com.google.gson.JsonObject loom = new com.google.gson.JsonObject();
		com.google.gson.JsonObject camp = new com.google.gson.JsonObject();
		com.google.gson.JsonObject soulcampo = new com.google.gson.JsonObject();
		com.google.gson.JsonObject scaff = new com.google.gson.JsonObject();
		com.google.gson.JsonObject compostor = new com.google.gson.JsonObject();
		com.google.gson.JsonObject astand = new com.google.gson.JsonObject();
		com.google.gson.JsonObject glowframe = new com.google.gson.JsonObject();
		com.google.gson.JsonObject frame = new com.google.gson.JsonObject();
		com.google.gson.JsonObject paint = new com.google.gson.JsonObject();
		com.google.gson.JsonObject lect = new com.google.gson.JsonObject();
		com.google.gson.JsonObject flowers = new com.google.gson.JsonObject();
		com.google.gson.JsonObject leaves = new com.google.gson.JsonObject();
		com.google.gson.JsonObject blaze = new com.google.gson.JsonObject();
		com.google.gson.JsonObject cItemOBJ = new com.google.gson.JsonObject();
		com.google.gson.JsonObject furnaceGenOBJ = new com.google.gson.JsonObject();
		com.google.gson.JsonObject fgenFP = new com.google.gson.JsonObject();
		com.google.gson.JsonObject hangingsignsobj = new com.google.gson.JsonObject();
		com.google.gson.JsonObject egenobj = new com.google.gson.JsonObject();
		com.google.gson.JsonObject egenfp = new com.google.gson.JsonObject();
		com.google.gson.JsonObject lfegen = new com.google.gson.JsonObject();
		com.google.gson.JsonObject ogenfp = new com.google.gson.JsonObject();
		com.google.gson.JsonObject ogenobj = new com.google.gson.JsonObject();
		com.google.gson.JsonObject nsgenobj = new com.google.gson.JsonObject();
		com.google.gson.JsonObject nsgenfp = new com.google.gson.JsonObject();
		com.google.gson.JsonObject cgenobj = new com.google.gson.JsonObject();
		com.google.gson.JsonObject cgenfp = new com.google.gson.JsonObject();
		com.google.gson.JsonObject degenfp = new com.google.gson.JsonObject();
		com.google.gson.JsonObject degenobj = new com.google.gson.JsonObject();
		com.google.gson.JsonObject exgenfp = new com.google.gson.JsonObject();
		com.google.gson.JsonObject exgen = new com.google.gson.JsonObject();
		com.google.gson.JsonArray sArray = new com.google.gson.JsonArray();
		com.google.gson.JsonArray cItemArray = new com.google.gson.JsonArray();
		com.google.gson.JsonArray fgenarray = new com.google.gson.JsonArray();
		com.google.gson.JsonArray earray = new com.google.gson.JsonArray();
		com.google.gson.JsonArray oarray = new com.google.gson.JsonArray();
		com.google.gson.JsonArray nsarray = new com.google.gson.JsonArray();
		com.google.gson.JsonArray cgenarray = new com.google.gson.JsonArray();
		com.google.gson.JsonArray dearray = new com.google.gson.JsonArray();
		com.google.gson.JsonArray exarray = new com.google.gson.JsonArray();
		configFile = new File((FMLPaths.GAMEDIR.get().toString() + "/config/euru/"), File.separator + "euru_fe_config.json");
		cVer = EuruModVariables.cVer;
		if (!configFile.exists()) {
			try {
				configFile.getParentFile().mkdirs();
				configFile.createNewFile();
			} catch (IOException exception) {
				exception.printStackTrace();
			}
			furnaceGenOBJ = FGenCFGManagerProcedure.execute();
			configJsonObject.add((BuiltInRegistries.ITEM.getKey(EuruModBlocks.FURNACE_GENERATOR.get().asItem()).toString()), furnaceGenOBJ);
			cItemOBJ = new com.google.gson.JsonObject();
			cItem = BuiltInRegistries.ITEM.getKey(Blocks.BARREL.asItem()).toString();
			cItemOBJ.addProperty("feGenerated", 600);
			cItemOBJ.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add(cItem, cItemOBJ);
			sArray.add(cItem);
			cItemOBJ = new com.google.gson.JsonObject();
			cItem = "minecraft:fence_gates";
			cItemOBJ.addProperty("feGenerated", 450);
			cItemOBJ.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add(cItem, cItemOBJ);
			sArray.add(cItem);
			cItemOBJ = new com.google.gson.JsonObject();
			cItem = "minecraft:banners";
			cItemOBJ.addProperty("feGenerated", 300);
			cItemOBJ.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add(cItem, cItemOBJ);
			sArray.add(cItem);
			cItemOBJ = new com.google.gson.JsonObject();
			cItem = BuiltInRegistries.ITEM.getKey(Items.FISHING_ROD).toString();
			cItemOBJ.addProperty("feGenerated", 200);
			cItemOBJ.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add(cItem, cItemOBJ);
			sArray.add(cItem);
			cItemOBJ = new com.google.gson.JsonObject();
			cItem = BuiltInRegistries.ITEM.getKey(Blocks.BAMBOO.asItem()).toString();
			cItemOBJ.addProperty("feGenerated", 100);
			cItemOBJ.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add(cItem, cItemOBJ);
			sArray.add(cItem);
			cItemOBJ = new com.google.gson.JsonObject();
			cItem = BuiltInRegistries.ITEM.getKey(Items.BLAZE_ROD).toString();
			cItemOBJ.addProperty("feGenerated", 20000);
			cItemOBJ.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add(cItem, cItemOBJ);
			sArray.add(cItem);
			sArray.add("minecraft:coals");
			sArray.add("minecraft:saplings");
			sArray.add("minecraft:logs");
			sArray.add("minecraft:planks");
			sArray.add((BuiltInRegistries.ITEM.getKey(Items.STICK).toString()));
			sArray.add("minecraft:wool");
			sArray.add("minecraft:hanging_signs");
			sArray.add("minecraft:wool_carpets");
			sArray.add((BuiltInRegistries.ITEM.getKey(Blocks.DAYLIGHT_DETECTOR.asItem()).toString()));
			sArray.add((BuiltInRegistries.ITEM.getKey(Items.WOODEN_AXE).toString()));
			sArray.add((BuiltInRegistries.ITEM.getKey(Items.WOODEN_SWORD).toString()));
			sArray.add((BuiltInRegistries.ITEM.getKey(Items.WOODEN_PICKAXE).toString()));
			sArray.add((BuiltInRegistries.ITEM.getKey(Items.WOODEN_SHOVEL).toString()));
			sArray.add((BuiltInRegistries.ITEM.getKey(Items.WOODEN_HOE).toString()));
			sArray.add((BuiltInRegistries.ITEM.getKey(Items.SHIELD).toString()));
			sArray.add((BuiltInRegistries.ITEM.getKey(Items.CARROT_ON_A_STICK).toString()));
			sArray.add((BuiltInRegistries.ITEM.getKey(Items.WARPED_FUNGUS_ON_A_STICK).toString()));
			sArray.add((BuiltInRegistries.ITEM.getKey(Blocks.BOOKSHELF.asItem()).toString()));
			sArray.add((BuiltInRegistries.ITEM.getKey(Blocks.CHISELED_BOOKSHELF.asItem()).toString()));
			sArray.add("minecraft:wooden_buttons");
			sArray.add("minecraft:wooden_doors");
			sArray.add("minecraft:wooden_fences");
			sArray.add("minecraft:wooden_pressure_plates");
			sArray.add("minecraft:wooden_slabs");
			sArray.add("minecraft:wooden_stairs");
			sArray.add("minecraft:wooden_trapdoors");
			sArray.add((BuiltInRegistries.ITEM.getKey(Blocks.COAL_BLOCK.asItem()).toString()));
			sArray.add((BuiltInRegistries.ITEM.getKey(Blocks.CRAFTING_TABLE.asItem()).toString()));
			sArray.add((BuiltInRegistries.ITEM.getKey(Blocks.CHEST.asItem()).toString()));
			sArray.add((BuiltInRegistries.ITEM.getKey(Blocks.TRAPPED_CHEST.asItem()).toString()));
			sArray.add((BuiltInRegistries.ITEM.getKey(Blocks.LADDER.asItem()).toString()));
			sArray.add((BuiltInRegistries.ITEM.getKey(Blocks.JUKEBOX.asItem()).toString()));
			sArray.add((BuiltInRegistries.ITEM.getKey(Blocks.BEEHIVE.asItem()).toString()));
			sArray.add("minecraft:beds");
			sArray.add((BuiltInRegistries.ITEM.getKey(Items.BOWL).toString()));
			sArray.add("minecraft:signs");
			sArray.add("minecraft:boats");
			sArray.add((BuiltInRegistries.ITEM.getKey(Items.BOW).toString()));
			sArray.add((BuiltInRegistries.ITEM.getKey(Items.CROSSBOW).toString()));
			sArray.add((BuiltInRegistries.ITEM.getKey(Items.TORCH).toString()));
			sArray.add((BuiltInRegistries.ITEM.getKey(Items.REDSTONE_TORCH).toString()));
			sArray.add((BuiltInRegistries.ITEM.getKey(Items.SOUL_TORCH).toString()));
			sArray.add((BuiltInRegistries.ITEM.getKey(Blocks.CARTOGRAPHY_TABLE.asItem()).toString()));
			sArray.add((BuiltInRegistries.ITEM.getKey(Blocks.FLETCHING_TABLE.asItem()).toString()));
			sArray.add((BuiltInRegistries.ITEM.getKey(Blocks.SMITHING_TABLE.asItem()).toString()));
			sArray.add((BuiltInRegistries.ITEM.getKey(Blocks.LOOM.asItem()).toString()));
			sArray.add((BuiltInRegistries.ITEM.getKey(Blocks.CAMPFIRE.asItem()).toString()));
			sArray.add((BuiltInRegistries.ITEM.getKey(Blocks.SOUL_CAMPFIRE.asItem()).toString()));
			sArray.add((BuiltInRegistries.ITEM.getKey(Blocks.SCAFFOLDING.asItem()).toString()));
			sArray.add((BuiltInRegistries.ITEM.getKey(Blocks.COMPOSTER.asItem()).toString()));
			sArray.add((BuiltInRegistries.ITEM.getKey(Items.ARMOR_STAND).toString()));
			sArray.add((BuiltInRegistries.ITEM.getKey(Items.GLOW_ITEM_FRAME).toString()));
			sArray.add((BuiltInRegistries.ITEM.getKey(Items.ITEM_FRAME).toString()));
			sArray.add((BuiltInRegistries.ITEM.getKey(Items.PAINTING).toString()));
			sArray.add((BuiltInRegistries.ITEM.getKey(Blocks.LECTERN.asItem()).toString()));
			sArray.add("minecraft:flowers");
			sArray.add("minecraft:leaves");
			leaves.addProperty("feGenerated", 80);
			leaves.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add("minecraft:leaves", leaves);
			hangingsignsobj.addProperty("feGenerated", 350);
			hangingsignsobj.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add("minecraft:hanging_signs", hangingsignsobj);
			flowers.addProperty("feGenerated", 80);
			flowers.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add("minecraft:flowers", flowers);
			lect.addProperty("feGenerated", 350);
			lect.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Blocks.LECTERN.asItem()).toString()), lect);
			paint.addProperty("feGenerated", 200);
			paint.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Items.PAINTING).toString()), paint);
			frame.addProperty("feGenerated", 200);
			frame.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Items.ITEM_FRAME).toString()), frame);
			glowframe.addProperty("feGenerated", 200);
			glowframe.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Items.GLOW_ITEM_FRAME).toString()), glowframe);
			astand.addProperty("feGenerated", 200);
			astand.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Items.ARMOR_STAND).toString()), astand);
			compostor.addProperty("feGenerated", 350);
			compostor.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Blocks.COMPOSTER.asItem()).toString()), compostor);
			scaff.addProperty("feGenerated", 350);
			scaff.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Blocks.SCAFFOLDING.asItem()).toString()), scaff);
			soulcampo.addProperty("feGenerated", 350);
			soulcampo.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Blocks.SOUL_CAMPFIRE.asItem()).toString()), soulcampo);
			camp.addProperty("feGenerated", 350);
			camp.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Blocks.CAMPFIRE.asItem()).toString()), camp);
			loom.addProperty("feGenerated", 350);
			loom.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Blocks.LOOM.asItem()).toString()), loom);
			smith.addProperty("feGenerated", 350);
			smith.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Blocks.SMITHING_TABLE.asItem()).toString()), smith);
			fletch.addProperty("feGenerated", 350);
			fletch.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Blocks.FLETCHING_TABLE.asItem()).toString()), fletch);
			cart.addProperty("feGenerated", 350);
			cart.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Blocks.CARTOGRAPHY_TABLE.asItem()).toString()), cart);
			torch.addProperty("feGenerated", 100);
			torch.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Items.TORCH).toString()), torch);
			torchred.addProperty("feGenerated", 100);
			torchred.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Items.REDSTONE_TORCH).toString()), torchred);
			torchsoul.addProperty("feGenerated", 100);
			torchsoul.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Items.SOUL_TORCH).toString()), torchsoul);
			beehive.addProperty("feGenerated", 400);
			beehive.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Blocks.BEEHIVE.asItem()).toString()), beehive);
			beds.addProperty("feGenerated", 600);
			beds.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add("minecraft:beds", beds);
			cbow.addProperty("feGenerated", 200);
			cbow.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Items.CROSSBOW).toString()), cbow);
			bow.addProperty("feGenerated", 200);
			bow.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Items.BOW).toString()), bow);
			boats.addProperty("feGenerated", 600);
			boats.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add("minecraft:boats", boats);
			signs.addProperty("feGenerated", 350);
			signs.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add("minecraft:signs", signs);
			bowl.addProperty("feGenerated", 200);
			bowl.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Items.BOWL).toString()), bowl);
			juke.addProperty("feGenerated", 350);
			juke.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Blocks.JUKEBOX.asItem()).toString()), juke);
			ladder.addProperty("feGenerated", 350);
			ladder.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Blocks.LADDER.asItem()).toString()), ladder);
			tchest.addProperty("feGenerated", 700);
			tchest.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Blocks.TRAPPED_CHEST.asItem()).toString()), tchest);
			chest.addProperty("feGenerated", 700);
			chest.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Blocks.CHEST.asItem()).toString()), chest);
			craft.addProperty("feGenerated", 350);
			craft.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Blocks.CRAFTING_TABLE.asItem()).toString()), craft);
			coalblock.addProperty("feGenerated", 23000);
			coalblock.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Blocks.COAL_BLOCK.asItem()).toString()), coalblock);
			wooden_trapdoors.addProperty("feGenerated", 350);
			wooden_trapdoors.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add("minecraft:wooden_trapdoors", wooden_trapdoors);
			wooden_stairs.addProperty("feGenerated", 350);
			wooden_stairs.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add("minecraft:wooden_stairs", wooden_stairs);
			wooden_slabs.addProperty("feGenerated", 175);
			wooden_slabs.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add("minecraft:wooden_slabs", wooden_slabs);
			wooden_pressure_plates.addProperty("feGenerated", 200);
			wooden_pressure_plates.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add("minecraft:wooden_pressure_plates", wooden_pressure_plates);
			wooden_fences.addProperty("feGenerated", 450);
			wooden_fences.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add("minecraft:wooden_fences", wooden_fences);
			wooden_doors.addProperty("feGenerated", 800);
			wooden_doors.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add("minecraft:wooden_doors", wooden_doors);
			button.addProperty("feGenerated", 80);
			button.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add("minecraft:wooden_buttons", button);
			cbookshelf.addProperty("feGenerated", 200);
			cbookshelf.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Blocks.CHISELED_BOOKSHELF.asItem()).toString()), cbookshelf);
			bookshelf.addProperty("feGenerated", 200);
			bookshelf.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Blocks.BOOKSHELF.asItem()).toString()), bookshelf);
			warpstick.addProperty("feGenerated", 200);
			warpstick.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Items.WARPED_FUNGUS_ON_A_STICK).toString()), warpstick);
			stickcarrot.addProperty("feGenerated", 200);
			stickcarrot.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Items.CARROT_ON_A_STICK).toString()), stickcarrot);
			shield.addProperty("feGenerated", 1200);
			shield.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Items.SHIELD).toString()), shield);
			whoe.addProperty("feGenerated", 400);
			whoe.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Items.WOODEN_HOE).toString()), whoe);
			wsho.addProperty("feGenerated", 400);
			wsho.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Items.WOODEN_SHOVEL).toString()), wsho);
			wpick.addProperty("feGenerated", 400);
			wpick.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Items.WOODEN_PICKAXE).toString()), wpick);
			waxe.addProperty("feGenerated", 400);
			waxe.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Items.WOODEN_AXE).toString()), waxe);
			wsword.addProperty("feGenerated", 400);
			wsword.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Items.WOODEN_SWORD).toString()), wsword);
			day.addProperty("feGenerated", 400);
			day.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Blocks.DAYLIGHT_DETECTOR.asItem()).toString()), day);
			carpet.addProperty("feGenerated", 100);
			carpet.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add("minecraft:wool_carpets", carpet);
			wool.addProperty("feGenerated", 200);
			wool.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add("minecraft:wool", wool);
			stickobj.addProperty("feGenerated", 100);
			stickobj.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add((BuiltInRegistries.ITEM.getKey(Items.STICK).toString()), stickobj);
			planksobj.addProperty("feGenerated", 350);
			planksobj.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add("minecraft:planks", planksobj);
			logsobj.addProperty("feGenerated", 350);
			logsobj.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add("minecraft:logs", logsobj);
			coalOBJ.addProperty("feGenerated", 2500);
			coalOBJ.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add("minecraft:coals", coalOBJ);
			saplingsobj.addProperty("feGenerated", 175);
			saplingsobj.addProperty("feSpeed", 5);
			fuelPropertiesOBJ.add("minecraft:saplings", saplingsobj);
			configSubJsonObjest.add("listFuel", sArray);
			configSubJsonObjest.add("fuelProperties", fuelPropertiesOBJ);
			configJsonObject.add((BuiltInRegistries.ITEM.getKey(EuruModBlocks.SURVIVAL_GENERATOR.get().asItem()).toString()), configSubJsonObjest);
			cgenobj = CGenCFGManagerProcedure.execute();
			configJsonObject.add((BuiltInRegistries.ITEM.getKey(EuruModBlocks.CULINARY_GENERATOR.get().asItem()).toString()), cgenobj);
			cItem = BuiltInRegistries.ITEM.getKey(Items.NETHER_STAR).toString();
			cItemOBJ = new com.google.gson.JsonObject();
			cItemOBJ.addProperty("feGenerated", 480000);
			cItemOBJ.addProperty("feSpeed", 1600);
			nsgenfp.add(cItem, cItemOBJ);
			nsarray.add(cItem);
			nsgenobj.add("listFuel", nsarray);
			nsgenobj.add("fuelProperties", nsgenfp);
			configJsonObject.add((BuiltInRegistries.ITEM.getKey(EuruModBlocks.NETHERSTAR_GENERATOR.get().asItem()).toString()), nsgenobj);
			cItem = BuiltInRegistries.ITEM.getKey(Items.GUNPOWDER).toString();
			cItemOBJ = new com.google.gson.JsonObject();
			cItemOBJ.addProperty("feGenerated", 1200);
			cItemOBJ.addProperty("feSpeed", 60);
			exgenfp.add(cItem, cItemOBJ);
			exarray.add(cItem);
			cItem = BuiltInRegistries.ITEM.getKey(Blocks.TNT.asItem()).toString();
			cItemOBJ = new com.google.gson.JsonObject();
			cItemOBJ.addProperty("feGenerated", 12000);
			cItemOBJ.addProperty("feSpeed", 160);
			exgenfp.add(cItem, cItemOBJ);
			exarray.add(cItem);
			cItem = BuiltInRegistries.ITEM.getKey(Items.TNT_MINECART).toString();
			cItemOBJ = new com.google.gson.JsonObject();
			cItemOBJ.addProperty("feGenerated", 13000);
			cItemOBJ.addProperty("feSpeed", 160);
			exgenfp.add(cItem, cItemOBJ);
			exarray.add(cItem);
			exgen.addProperty("explosion_chance", 2.5);
			exgen.add("listFuel", exarray);
			exgen.add("fuelProperties", exgenfp);
			configJsonObject.add((BuiltInRegistries.ITEM.getKey(EuruModBlocks.EXPLOSIVE_GENERATOR.get().asItem()).toString()), exgen);
			cItem = "math_-Dont_touch_this_if_you_dont_know_what_youre_doing";
			cItemOBJ = new com.google.gson.JsonObject();
			cItemOBJ.addProperty("currentWeight", 1.68);
			cItemOBJ.addProperty("totalFEGenerated", 24000);
			degenfp.add(cItem, cItemOBJ);
			dearray.add(cItem);
			degenfp.addProperty("feSpeed", 140);
			degenobj.add("listFuel", dearray);
			degenfp.addProperty("feIncrement", 20);
			degenobj.add("fuelProperties", degenfp);
			configJsonObject.add((BuiltInRegistries.ITEM.getKey(EuruModBlocks.DISENCHANTMENT_GENERATOR.get().asItem()).toString()), degenobj);
			cItem = BuiltInRegistries.ITEM.getKey(EuruModItems.ENDER_SHARD.get()).toString();
			cItemOBJ = new com.google.gson.JsonObject();
			cItemOBJ.addProperty("feGenerated", 1000);
			cItemOBJ.addProperty("feSpeed", 80);
			egenfp.add(cItem, cItemOBJ);
			earray.add(cItem);
			cItem = BuiltInRegistries.ITEM.getKey(Items.ENDER_EYE).toString();
			cItemOBJ = new com.google.gson.JsonObject();
			cItemOBJ.addProperty("feGenerated", 12000);
			cItemOBJ.addProperty("feSpeed", 120);
			egenfp.add(cItem, cItemOBJ);
			earray.add(cItem);
			cItem = BuiltInRegistries.ITEM.getKey(Items.ENDER_PEARL).toString();
			cItemOBJ = new com.google.gson.JsonObject();
			cItemOBJ.addProperty("feGenerated", 8000);
			cItemOBJ.addProperty("feSpeed", 80);
			egenfp.add(cItem, cItemOBJ);
			earray.add(cItem);
			egenobj.add("listFuel", earray);
			egenobj.add("fuelProperties", egenfp);
			configJsonObject.add((BuiltInRegistries.ITEM.getKey(EuruModBlocks.ENDER_GENERATOR.get().asItem()).toString()), egenobj);
			ogenobj = OGenCFGManagerProcedure.execute();
			configJsonObject.add((BuiltInRegistries.ITEM.getKey(EuruModBlocks.OVERCLOCKED_GENERATOR.get().asItem()).toString()), ogenobj);
			configJsonObject.addProperty("config_version", cVer);
			{
				com.google.gson.Gson mainGSONBuilderVariable = new com.google.gson.GsonBuilder().setPrettyPrinting().create();
				try {
					FileWriter fileWriter = new FileWriter(configFile);
					fileWriter.write(mainGSONBuilderVariable.toJson(configJsonObject));
					fileWriter.close();
				} catch (IOException exception) {
					exception.printStackTrace();
				}
			}
		} else {
			{
				try {
					BufferedReader bufferedReader = new BufferedReader(new FileReader(configFile));
					StringBuilder jsonstringbuilder = new StringBuilder();
					String line;
					while ((line = bufferedReader.readLine()) != null) {
						jsonstringbuilder.append(line);
					}
					bufferedReader.close();
					configJsonObject = new com.google.gson.Gson().fromJson(jsonstringbuilder.toString(), com.google.gson.JsonObject.class);
					if (configJsonObject.get("config_version").isJsonPrimitive() ? configJsonObject.get("config_version").getAsJsonPrimitive().isNumber() : false) {
						if (configJsonObject.get("config_version").getAsDouble() != cVer) {
							configFile.delete();
							EURUGeneratorsManagerProcedure.execute();
						}
					} else {
						configFile.delete();
						EURUGeneratorsManagerProcedure.execute();
					}
				} catch (IOException e) {
					e.printStackTrace();
				}
			}
		}
	}
}