package net.wavedk.extrautilitiesreutilized.procedures;

import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.item.Items;
import net.minecraft.core.registries.BuiltInRegistries;

public class FGenCFGManagerProcedure {
	public static com.google.gson.JsonObject execute() {
		com.google.gson.JsonObject cItemOBJ = new com.google.gson.JsonObject();
		com.google.gson.JsonObject fgenFP = new com.google.gson.JsonObject();
		com.google.gson.JsonObject furnaceGenOBJ = new com.google.gson.JsonObject();
		com.google.gson.JsonObject configJsonObject = new com.google.gson.JsonObject();
		com.google.gson.JsonArray fgenarray = new com.google.gson.JsonArray();
		String cItem = "";
		cItem = BuiltInRegistries.ITEM.getKey(Blocks.LADDER.asItem()).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 180);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.GLOW_ITEM_FRAME).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 180);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.ITEM_FRAME).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 180);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.PAINTING).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 180);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.ARMOR_STAND).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 180);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = "minecraft:wooden_fences";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 250);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = "minecraft:fence_gates";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 250);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = "minecraft:wooden_trapdoors";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 250);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = "minecraft:wooden_pressure_plates";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 180);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = "minecraft:hanging_signs";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = "minecraft:signs";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = "minecraft:wooden_doors";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 800);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.CROSSBOW).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 200);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.BOW).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 200);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.WOODEN_HOE).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 500);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.WOODEN_AXE).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 500);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.WOODEN_SHOVEL).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 500);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.WOODEN_PICKAXE).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 500);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.WOODEN_SWORD).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 500);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = "minecraft:banners";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 250);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = "minecraft:wooden_slabs";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 250);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = "minecraft:leaves";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 120);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = "minecraft:flowers";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 80);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = "minecraft:beds";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 400);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Blocks.SCAFFOLDING.asItem()).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Blocks.CHISELED_BOOKSHELF.asItem()).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Blocks.BOOKSHELF.asItem()).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Blocks.CARTOGRAPHY_TABLE.asItem()).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Blocks.FLETCHING_TABLE.asItem()).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Blocks.SMITHING_TABLE.asItem()).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Blocks.LOOM.asItem()).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Blocks.CRAFTING_TABLE.asItem()).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = "minecraft:logs";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = "minecraft:wooden_stairs";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = "minecraft:boats";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 600);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Blocks.COAL_BLOCK.asItem()).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 14000);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Blocks.BARREL.asItem()).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Blocks.LECTERN.asItem()).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Blocks.COMPOSTER.asItem()).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Blocks.TRAPPED_CHEST.asItem()).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Blocks.CHEST.asItem()).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = "minecraft:planks";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = "minecraft:wooden_buttons";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 150);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.BOWL).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 150);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.CARROT_ON_A_STICK).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.WARPED_FUNGUS_ON_A_STICK).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.FISHING_ROD).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Blocks.BAMBOO.asItem()).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 100);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.STICK).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 100);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = "minecraft:saplings";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 200);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = "minecraft:wool";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 260);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = "minecraft:wool_carpets";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 150);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = "minecraft:coals";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 1500);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.BLAZE_ROD).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 16000);
		cItemOBJ.addProperty("feSpeed", 20);
		fgenFP.add(cItem, cItemOBJ);
		fgenarray.add(cItem);
		furnaceGenOBJ.add("listFuel", fgenarray);
		furnaceGenOBJ.add("fuelProperties", fgenFP);
		return furnaceGenOBJ;
	}
}