package net.wavedk.extrautilitiesreutilized.procedures;

import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.item.Items;
import net.minecraft.core.registries.BuiltInRegistries;

public class OGenCFGManagerProcedure {
	public static com.google.gson.JsonObject execute() {
		com.google.gson.JsonObject cItemOBJ = new com.google.gson.JsonObject();
		com.google.gson.JsonObject configJsonObject = new com.google.gson.JsonObject();
		com.google.gson.JsonObject ogenfp = new com.google.gson.JsonObject();
		com.google.gson.JsonObject ogenobj = new com.google.gson.JsonObject();
		String cItem = "";
		com.google.gson.JsonArray oarray = new com.google.gson.JsonArray();
		cItem = "minecraft:wooden_trapdoors";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 200);
		cItemOBJ.addProperty("feSpeed", 200);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = "minecraft:wooden_pressure_plates";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 200);
		cItemOBJ.addProperty("feSpeed", 200);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = "minecraft:wooden_doors";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 200);
		cItemOBJ.addProperty("feSpeed", 200);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = "minecraft:wooden_stairs";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 300);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.WOODEN_SWORD).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 200);
		cItemOBJ.addProperty("feSpeed", 200);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.WOODEN_SHOVEL).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 200);
		cItemOBJ.addProperty("feSpeed", 200);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.WOODEN_PICKAXE).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 200);
		cItemOBJ.addProperty("feSpeed", 200);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.WOODEN_HOE).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 200);
		cItemOBJ.addProperty("feSpeed", 200);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.WOODEN_AXE).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 200);
		cItemOBJ.addProperty("feSpeed", 200);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.WARPED_FUNGUS_ON_A_STICK).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 300);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Blocks.SMITHING_TABLE.asItem()).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 300);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Blocks.SCAFFOLDING.asItem()).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 100);
		cItemOBJ.addProperty("feSpeed", 100);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.PAINTING).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 100);
		cItemOBJ.addProperty("feSpeed", 100);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Blocks.NOTE_BLOCK.asItem()).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 300);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Blocks.LOOM.asItem()).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 300);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Blocks.LECTERN.asItem()).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 300);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Blocks.LADDER.asItem()).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 300);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Blocks.JUKEBOX.asItem()).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 300);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = "minecraft:hanging_signs";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 200);
		cItemOBJ.addProperty("feSpeed", 200);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = "minecraft:signs";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 200);
		cItemOBJ.addProperty("feSpeed", 200);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.ITEM_FRAME).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 100);
		cItemOBJ.addProperty("feSpeed", 100);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.GLOW_ITEM_FRAME).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 100);
		cItemOBJ.addProperty("feSpeed", 100);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = "minecraft:flowers";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 60);
		cItemOBJ.addProperty("feSpeed", 60);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Blocks.FLETCHING_TABLE.asItem()).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 300);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.FISHING_ROD).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 300);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.CROSSBOW).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 300);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Blocks.CRAFTING_TABLE.asItem()).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 300);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Blocks.COMPOSTER.asItem()).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 300);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Blocks.CHISELED_BOOKSHELF.asItem()).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 300);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Blocks.CHEST.asItem()).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 300);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = "minecraft:coals";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 1200);
		cItemOBJ.addProperty("feSpeed", 1200);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Blocks.CARTOGRAPHY_TABLE.asItem()).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 300);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.CARROT_ON_A_STICK).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 300);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = "minecraft:wooden_buttons";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 100);
		cItemOBJ.addProperty("feSpeed", 100);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.BOWL).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 100);
		cItemOBJ.addProperty("feSpeed", 100);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.BOW).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 300);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Blocks.BOOKSHELF.asItem()).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 300);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = "minecraft:boats";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 400);
		cItemOBJ.addProperty("feSpeed", 400);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.BLAZE_ROD).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 2000);
		cItemOBJ.addProperty("feSpeed", 2000);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = "minecraft:beds";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 400);
		cItemOBJ.addProperty("feSpeed", 400);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Blocks.BARREL.asItem()).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 300);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = "minecraft:banners";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 300);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.STICK).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 60);
		cItemOBJ.addProperty("feSpeed", 60);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Blocks.BAMBOO.asItem()).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 60);
		cItemOBJ.addProperty("feSpeed", 60);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Items.ARMOR_STAND).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 300);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = "minecraft:wool";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 100);
		cItemOBJ.addProperty("feSpeed", 100);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = "minecraft:wooden_slabs";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 300);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = "minecraft:planks";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 300);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = "minecraft:saplings";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 100);
		cItemOBJ.addProperty("feSpeed", 100);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = "minecraft:logs";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 300);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Blocks.TRAPPED_CHEST.asItem()).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 300);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Blocks.DAYLIGHT_DETECTOR.asItem()).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 300);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = "minecraft:wool_carpets";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 60);
		cItemOBJ.addProperty("feSpeed", 60);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = "minecraft:fence_gates";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 300);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = "minecraft:wooden_fences";
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 300);
		cItemOBJ.addProperty("feSpeed", 300);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		cItem = BuiltInRegistries.ITEM.getKey(Blocks.COAL_BLOCK.asItem()).toString();
		cItemOBJ = new com.google.gson.JsonObject();
		cItemOBJ.addProperty("feGenerated", 8000);
		cItemOBJ.addProperty("feSpeed", 2000);
		ogenfp.add(cItem, cItemOBJ);
		oarray.add(cItem);
		ogenobj.add("listFuel", oarray);
		ogenobj.add("fuelProperties", ogenfp);
		return ogenobj;
	}
}